AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates resources for Unity Catalog in your AWS account.

Metadata:
  QuickStartDocumentation:
    EntrypointName: "Resources for Unity Catalog"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "UC configuration"
        Parameters:
          - AccountId
          - AWSRegion
      - Label:
          default: "Required IAM role and S3 bucket configuration"  
        Parameters:
          - IAMRole
          - BucketName    
    ParameterLabels:
      AccountId:
        default: Databricks account ID
      AWSRegion:
        default: AWS Region of the Databricks workspace   
      IAMRole:
        default: Cross-account IAM role name
      BucketName:
        default: Root S3 bucket name   

Parameters:
  AccountId:
    Description: "You can find your account ID at https://accounts.cloud.databricks.com" 
    AllowedPattern: '^[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$'
    MinLength: '36'
    Type: String
    Default: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
  AWSRegion:
    Description: "AWS Region where the workspace will be created."
    MinLength: '9'
    AllowedValues:
       - ap-northeast-1
       - ap-south-1
       - ap-southeast-2
       - ca-central-1
       - eu-central-1
       - eu-west-1
       - eu-west-2
       - us-east-1
       - us-east-2
       - us-west-1
       - us-west-2
    Type: String  
  IAMRole:
    Description: "Specify a unique cross-account IAM role name. For naming rules, see https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html."
    AllowedPattern: '[\w+=,@-]+'
    Type: String
    MinLength: '1'
    MaxLength: '64'
  BucketName:
    Description: "Specify a unique name for the S3 bucket where Databricks will store metadata for your workspace. Use only alphanumeric characters. For naming rules, see https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html."
    AllowedPattern: '(?=^.{3,63}$)(?!xn--)([a-z0-9](?:[a-z0-9-]*)[a-z0-9])$'
    MinLength: '3'
    MaxLength: '63'
    Type: String
    ConstraintDescription: The UC bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
 

Rules:
# Validate the selected Region from the drop-down matches the Region from the Console
  RunningTemplateFromDifferentRegionThanDropDown:
    Assertions:
    - Assert: !Equals [!Ref AWSRegion, !Ref 'AWS::Region']
      AssertDescription: "The region from the AWS Management Console MUST be the same as the selected region from the drop-down."

Resources:
  # Cross-account access role for Databricks UC
  CrossAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref IAMRole
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Condition:
              StringEquals: 
                'sts:ExternalId': !Sub '${AccountId}'
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - '414351767826'
                  - ':root'
            Sid: ''
        Version: 2012-10-17
      Path: /
      Policies:   
        - PolicyDocument:    
            Statement:
              - Sid: GrantAccess
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                Resource:
                  - !Sub 'arn:aws:s3:::${assetsS3Bucket}/*'
                  - !Sub 'arn:aws:s3:::${assetsS3Bucket}'
              - Sid: DatabricksSampleData  
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                Resource:
                  - 'arn:aws:s3:::databricks-corp-training/*'
                  - 'arn:aws:s3:::databricks-corp-training'  
            Version: 2012-10-17        
          PolicyName: databricks-uc-policy    
      

  # S3 root bucket requirements
  assetsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls       : true
        BlockPublicPolicy     : true
        IgnorePublicAcls      : true
        RestrictPublicBuckets : true     
                         

  